[window]
opacity = 0.8

[colors]
transparent_background_colors = true

[colors.primary]
background = "#14101c"
foreground = "#b8a3e0"

[colors.normal]
black   = "#14101c"
red     = "#b45cd8"
green   = "#7c6ca0"
yellow  = "#c77df0"
blue    = "#6c4ca0"
magenta = "#9a4fd0"
cyan    = "#6a6580"
white   = "#7565a0"

[colors.bright]
black   = "#45395f"
red     = "#b45cd8"
green   = "#7c6ca0"
yellow  = "#c77df0"
blue    = "#6c4ca0"
magenta = "#9a4fd0"
cyan    = "#6a6580"
white   = "#b8a3e0"

[colors.cursor]
text   = "#14101c"
cursor = "#7565a0"

[colors.vi_mode_cursor]
text   = "#14101c"
cursor = "#7565a0"

[colors.search.matches]
foreground = "#14101c"
background = "#c77df0"

[colors.search.focused_match]
foreground = "#14101c"
background = "#b45cd8"

[colors.footer_bar]
foreground = "#14101c"
background = "#b8a3e0"

[colors.selection]
text = "#c77df0"
background = "#6c4ca0"
