accent = "#6c4ca0"
cursor = "#7565a0"
foreground = "#b8a3e0"
background = "#14101c"
selection_foreground = "#c77df0"
selection_background = "#6c4ca0"

color0 = "#14101c"
color1 = "#b45cd8"
color2 = "#7c6ca0"
color3 = "#c77df0"
color4 = "#6c4ca0"
color5 = "#9a4fd0"
color6 = "#6a6580"
color7 = "#7565a0"
color8 = "#45395f"
color9 = "#b45cd8"
color10 = "#7c6ca0"
color11 = "#c77df0"
color12 = "#6c4ca0"
color13 = "#9a4fd0"
color14 = "#6a6580"
color15 = "#b8a3e0"
