background = #14101c
foreground = #b8a3e0
cursor-color = #7565a0
selection-background = #6c4ca0
selection-foreground = #c77df0
background-opacity = 0.8

palette = 0=#14101c
palette = 1=#b45cd8
palette = 2=#7c6ca0
palette = 3=#c77df0
palette = 4=#6c4ca0
palette = 5=#9a4fd0
palette = 6=#6a6580
palette = 7=#7565a0

palette = 8=#45395f
palette = 9=#b45cd8
palette = 10=#7c6ca0
palette = 11=#c77df0
palette = 12=#6c4ca0
palette = 13=#9a4fd0
palette = 14=#6a6580
palette = 15=#b8a3e0